### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot perform Construct on a detached ArrayBuffer

### ISSUE THREAD

**Issue by Grajon** [stephanrauh/ngx-extended-pdf-viewer#1682]
the error occurs when switching between 2 PDFs, also on the demo site (https://pdfviewer.net/extended-pdf-viewer/blob) with both versions of pdf.js

the PDF is loaded and displayed but on the javascript console (Chrome and Firefox 110 64bits) we can see an error :

Uncaught (in promise) TypeError: Cannot perform Construct on a detached ArrayBuffer
    at new Uint8Array (<anonymous>)
    at getDocument (viewer-3.4.406.min.js:23:18926)
    at viewer-3.4.406.min.js:44:33498
    at v.invoke (polyfills.fde04a9f7be3cdbd.js:1:6589)
    at M.run (polyfills.fde04a9f7be3cdbd.js:1:1955)
    at Yo.runOutsideAngular (main.942c0772d475710e.js:1:365590)
    at Object.open (viewer-3.4.406.min.js:44:32944)
    at main.942c0772d475710e.js:1:1371119
    at Generator.next (<anonymous>)
    at a (main.942c0772d475710e.js:1:1446434)
...

**Comment by stephanrauh** [comment]
Indeed. Weird. After a cursory glance, I suspect that the document is opened multiple times, and the last call has valid parameters.

**Comment by stephanrauh** [comment]
BTW, the error message does not appear on https://pdfviewer.net/extended-pdf-viewer/multiple-documents. It's probably specific to BLOBs.

**Comment by stephanrauh** [comment]
@Grajon Please update to version 16.2.0. It seems I've neglected my bookkeeping, but I'm pretty sure I've fixed your bug one or two weeks ago. Can you have a look, please?

Thanks in advance,
Stephan

**Comment by Grajon** [comment]
Sorry but I have the 16.2.1 version and the error is always here : 

![image](https://user-images.githubusercontent.com/6169456/221843009-1288157a-9b69-4b98-b236-b06ff44f2b65.png)

**Comment by Grajon** [comment]
I don't know which version you use on https://pdfviewer.net/extended-pdf-viewer/blob but the error is still there too

Thank you in advance for all your efforts
Grajon

**Comment by stephanrauh** [comment]
The error message of the showcase is slightly different. However, I've managed to get rid of it, so I hope your bug is a thing of the past soon.

**Comment by stephanrauh** [comment]
Your bugfix has landed with version 16.2.3.

Enjoy!
Stephan
