### ISSUE TITLE
'[(page)]="pageNumber" method is not working

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#2051]
Since version 19.0.3, '[(page)]="pageNumber" method is not working

_Originally posted by @dhananjay19100 in https://github.com/stephanrauh/ngx-extended-pdf-viewer/discussions/2014#discussioncomment-8047211_

**Comment by stephanrauh** [comment]
Solved with version 19.0.5. It seems `(pagesLoaded)` is broken, and this is a follow-up bug.

**Comment by priveraussi** [comment]
> Solved with version 19.0.5. It seems `(pagesLoaded)` is broken, and this is a follow-up bug.

Is the pagesLoaded output event still broken? I am not seeing it fire on 19.0.6.

**Comment by achapman009** [comment]
> Solved with version 19.0.5. It seems `(pagesLoaded)` is broken, and this is a follow-up bug.

Is the pagesLoaded output event still broken? I am not seeing it fire on 19.0.6.

**Comment by stephanrauh** [comment]
I don't have a clue what's going wrong, so I can't fix the event. A pdf.js promise I'm using stopped resolving.

Adding insult to injury, I've put the library to maintenance mode until somebody tells me what the EU Cyber Resilience Act means. If my library - being a derivative of a part of Firefox - has to fulfil the same obligation as a browser, I'll have to shut it down before the Act become effective. I'd appreciate legal advice (see #2049).
