### ISSUE TITLE
Unhandled Promise rejection: Promise.withResolvers is not a function

### ISSUE THREAD

**Issue by Congchuabongbong** [stephanrauh/ngx-extended-pdf-viewer#2301]
I am installing and testing version ^20.0.0-alpha.1 and see the error as shown in the picture: 
![image_2024_04_17T08_29_24_951Z](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/d55bae2a-b959-40d4-9bd4-aa63e0a15dab)
![image_2024_04_17T08_29_39_510Z](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/78024720/cf6443e6-ad99-40bb-832f-6a47c0f03958)

**Comment by stephanrauh** [comment]
Which browser are you using? According to https://caniuse.com/?search=promise.withResolvers, browser support should be pretty good - with the exception of Safari: only the latest version of Safari supports this method.
<img width="1454" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/9dfc2654-4d33-41a0-b74f-2fa77eafce52">

**Comment by Congchuabongbong** [comment]
Currently I'm using Chrome!

**Comment by stephanrauh** [comment]
Yes, you're right - I was blind yesterday, I should have seen it from your screenshot. Which version are you using?

**Comment by Congchuabongbong** [comment]
i'm using latest version! exactly it's 124.0.6367.61

**Comment by stephanrauh** [comment]
That's weird. Nonetheless, the `withResolvers()` function is fairly new, so it makes sense to check whether the browser supports it. I'm preparing a browser switch.

**Comment by Congchuabongbong** [comment]
Ok, I hope you will find the cause and I will also try to find the cause

**Comment by stephanrauh** [comment]
The improvement is going to land with version 20.0.0-alpha.2.

**Comment by stephanrauh** [comment]
Version 20.0.0-alpha.2 was buggy. It always used the ES5 version of the code. Version 20.0.0-alpha.3 uses a more clever approach.

**Comment by stephanrauh** [comment]
@SimonKunz That's nasty. We have to talk serious with zone.js! :) 

Jokes aside, I'm sure there's a way to solve it, but I'd like to talk you into finding the solution yourself and send me a pull request or to describe what I need to modify. I believe it's a task you can manage, and it helps me to catch up with the work that piled up during my vacations.

Browser detection happens in a file called `op-chaining-support.js`. That's a very simple class that runs some test. If they pass, the flag `window.ngxExtendedPdfViewerCanRunModernJSCode` is set to true, and otherwise the file crashed, so the flag remains undefined. Maybe you manage to call the `withResolvers()` function to enforce the crash, or you find a different class/method/function that has been introduced after Safari 17.4.

**Comment by ilgazil** [comment]
If it can help someone, we experienced the same problem.

We solved the case with setting `needsES5` option depending on the implementation of `Promise.withResolvers`. But in our environnement, we have a polyfill for this in our application environment that does not exist in the worker. The evaluation is a bit tricky, but the goal is to evaluate it outside our application environment (the main `window` object):

```ts
import {pdfDefaultOptions} from 'ngx-extended-pdf-viewer';

function useLegacyPdfViewer(): boolean {
  const iframe = document.createElement('iframe');
  document.firstElementChild.append(iframe);
  const useLegacyPdfViewer = 'withResolvers' in iframe.contentWindow['Promise'];
  iframe.parentElement.removeChild(iframe);

  return useLegacyPdfViewer;
}

pdfDefaultOptions.needsES5 = useLegacyPdfViewer();
```

**Comment by stephanrauh** [comment]
@ilgazil That's the cleanest solution I've seen so far. I'm going to add it to the browser detection file. Thanks for sharing!

**Comment by stephanrauh** [comment]
@ilgazil Version 21.0.0-alpha.3 now includes your code snippet - but with an important change: I think you've lost a negation when you pasted your code snippet here. If `'withResolvers' in iframe.contentWindow['Promise']`, then we can safely run the modern JS code.

**Comment by ilgazil** [comment]
😱 
Ha yes you're absolutely right, I missed something when cleaning the snippet from the noise of my app environment... Sorry about that! But glad to see it helped!

**Comment by stephanrauh** [comment]
I suppose I can close this ticket now. The issue is solved in the alpha versions only, but by the look of it, it's only a matter of time until the alpha version becomes a real version.

**Comment by dshakya** [comment]
The PDF does not load when I am using 21.0.0-alpha.3. It works until the alpha.2

I have tried the latest 21.0.0-beta.3 and it still doesn't load the PDF. Am I missing something? Any update on v21 release?

```
  <ngx-extended-pdf-viewer [src]="pdfUrl" [height]="'100%'" [showDownloadButton]="false" [showBorders]="false"
    [showOpenFileButton]="false" [showDrawEditor]="false" [showFreeFloatingBar]="false" [showHighlightEditor]="false"
    [showPresentationModeButton]="false" [showPropertiesButton]="false" [showTextEditor]="false"
    [showRotateButton]="false" [showToolbar]="true" [showSecondaryToolbarButton]="false" [showStampEditor]="false">
  </ngx-extended-pdf-viewer>
```

**Comment by stephanrauh** [comment]
@dshakya Which browser are you using? At the moment, I can't reproduce the issue - the viewer works flawlessly on current Chromes, Firefoxes, and Safaris.

**Comment by stephanrauh** [comment]
As for release 21: I think I can publish it now. I see roughly 1000 downloads of the beta version, and you're the first to report an error.

**Comment by dshakya** [comment]
I am using Chrome, Edge and Firefox. All giving me the same issue. But it works fine with alpha-2. Could be something at my end. Will test again with few other scenarios. 

I created a simple project on Stackblitz and it works there with latest beta. Will keep on testing.

https://stackblitz.com/edit/stackblitz-starters-srezuk?file=package.json

**Comment by stephanrauh** [comment]
You can also test the showcase with your browsers. If there's a general problem, it should also show here: https://pdfviewer.net/extended-pdf-viewer/base64

**Comment by dshakya** [comment]
Hi @stephanrauh ,

Thanks. I can see the showcase without any problem in my browsers. I wonder why this is throwing error for me from alpha.3 and beyond.

**Comment by dshakya** [comment]
Hi @stephanrauh ,

Just to test it out, I created a new angular project and added the latest (v21) version of the viewer. It works fine and I have displayed it in Material dialog exactly like my original project. 

What baffles me is what changed between alpha-2 and alpha-3 that is affecting my project. I thought it was maybe conflicting with other packages so I even added the jsPDF to the new project and it still works. Running out of debugging ideas here. Any pointers?

Many thanks for releasing the v21.

**Comment by dshakya** [comment]
Hi @stephanrauh ,

Wow, the solution to my problem was staring at me in this very thread. All I had to do was to update the zone.js to the latest version (0.14.8) from (0.14.2) and it works like a charm. No wonder my new projects worked as it has the latest version of it. Many thanks again!
