### ISSUE TITLE
Writing and scrolling at the same time for touch

### ISSUE THREAD

**Issue by legraina** [stephanrauh/ngx-extended-pdf-viewer#2597]
Hi Stephan,

I realized that the newest versions broke the annotation tool when using touch. In particular, it seems that the viewer wants to scroll and write at the same time when using touch (you can test it in you browser and simulating an iPad). I didn't have time to investigate which new version and modifications caused this issue. Perhaps later.

Antoine

**Comment by stephanrauh** [comment]
What? Oh no! You've fixed this a short time ago - or was it a different bug? https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2512

**Comment by legraina** [comment]
Yes, it's different. Some of the recent modifications broke the ink annotations when using the finger (can be tested on developer tools when selecting a tablet). I think the #boundCanvasTouchMove is not defined anymore in the viewer as some refactoring has been done. It just needs to be bound when adding the event "touchmove".
Unfortunately, I won't have the time to fix it soon (the fix should be super easy, but ensuring it works as it supposed a little more time-consuming).
Finally, I've seen the other events are not removed anymore. Is it normal? It's not slowing the application ?

**Comment by stephanrauh** [comment]
Ah, now I understand. Painting is not generally broken. It's "only" broken for your touch device. I was already wondering why there's no flood of similar issues.

The downside is that I don't know how to fix the issue. You know, if I can't reproduce it, fixing becomes a real challenge.

You may be right: the editor classes are fairly new, so there's a lot of refactoring going on there. However, I'm surprised that this includes the ink tool, because it's one of the oldest - and hopefully most mature - editor tools.

> Finally, I've seen the other events are not removed anymore. Is it normal? It's not slowing the application?

I'm afraid I don't understand the question. Are you talking about event listeners that are not tidied up when the component is destroyed? If so, that's a bug. More likely than not it's only a performance issue, but there might be unexpected side-effects.

BTW, please have a look at the bleeding edge branch. I've invented it as a canary branch so I (and helpful library users) can detect this kind of bug early.

**Comment by legraina** [comment]
> Ah, now I understand. Painting is not generally broken. It's "only" broken for your touch device. I was already wondering why there's no flood of similar issues.

I'm sorry to inform you that it's generally broken for the touch events .... If you go there (https://pdfviewer.net/extended-pdf-viewer/export-annotations) and use in the developer tools the ipad mode, you'll see it does not work because of the explanations I gave (#boundCanvasTouchMove is not defined anymore).

**Comment by legraina** [comment]
> I'm afraid I don't understand the question. Are you talking about event listeners that are not tidied up when the component is destroyed? If so, that's a bug. More likely than not it's only a performance issue, but there might be unexpected side-effects.

I don't find the removeEventListeners() anymore in the viewer.mjs.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by stephanrauh** [comment]
Version 22.0.0-alpha.6 fixes the issue. Please run a test - I'm not entirely sure I've been able to restore everything.

Best regards,
Stephan

**Comment by legraina** [comment]
Hi,

It seems ok, but you still have one bug that did not let me test it.
```
static initialize(t, e) {
    AnnotationEditor.initialize(t, e);
    setTimeout(( () => this.initializePointerType()))
}
```
You use ``this`` in a static method, so I have an error on my side.

**Comment by stephanrauh** [comment]
Oh, you're right. I've fixed that in version 22.0.0-alpha.7. It's weird that neither gulp nor VS Code complained about that.

I've tried to find the method `removeEventListeners()`. It seems it was never in my copy of the code. Which event listeners need to be removed?

**Comment by legraina** [comment]
Thanks, however, it's still not good. The way it's now implemented is not useful anymore. Before, ``enableEditMode()`` was only called when clicking on the annotation button, but now it's called every time we try to draw. The goal of ``initializePointerType()`` is to store the type of the pointer used when clicking on the button, so it should be called only when the button is clicked (which is not the case anymore for ``enableEditMode()``). Is it a bug or it's the intended behavior ? Do you now which method is only called when clicking on the annotation button ?

For the listeners, you add all those below, but it seems you are not removing them anymore.
```
this.canvas.addEventListener("pointerleave", this.canvasPointerleave.bind(this), {
      signal
    });
    this.canvas.addEventListener("pointermove", this.canvasPointermove.bind(this), {
      signal
    });
    this.canvas.addEventListener("pointerup", this.canvasPointerup.bind(this), {
      signal
    });
    this.canvas.addEventListener("touchmove", this.#boundCanvasTouchMove, {
      signal: this._uiManager._signal,
      passive: false
    });
```
Before, you were removing them, now, it seems you are only removing "touchmove".

**Comment by stephanrauh** [comment]
What an ugly merge hell!

**Comment by legraina** [comment]
I don't know what happened, but indeed :(

**Comment by stephanrauh** [comment]
Thing is, you've told me there used to be code removing the pointer events, but for some reason, I don't find it in the version history. Either I'm blind, or it was never there. I agree it should be there, it's just that I'm very confused and I wonder what else got lost.

**Comment by legraina** [comment]
I'm using version 21.3.8 (associated to commit e80d8f27353953d0554a088fab918f20b7890714), and the ``removeEventListener()`` calls are there.

**Comment by stephanrauh** [comment]
@legraina @Calixteman I've found it. There's an `AbortController` emitting a signal that automatically unsubscribes the listener. 
https://github.com/stephanrauh/pdf.js/commit/c0bf3d3c9454e4e3dcbae4080ab0a763b76d71b2

**Comment by calixteman** [comment]
For your information, I'm currently refactoring the ink editor to make it simpler and in order to prepare some future draw editors.
That said, here they're unregistered thanks to the AbortController.

**Comment by calixteman** [comment]
> @legraina @calixteman I've found it. There's an `AbortController` emitting a signal that automatically unsubscribes the listener. [stephanrauh/pdf.js@c0bf3d3](https://github.com/stephanrauh/pdf.js/commit/c0bf3d3c9454e4e3dcbae4080ab0a763b76d71b2)

Yeah AbortController simplified a lot listeners unregistration, especially when we want to clean up and even to avoid to keep some refs on the callbacks themselves. I'd recommend their use :).

**Comment by stephanrauh** [comment]
@calixteman @legraina To be honest, I'd like to throw away my modifications. Instead, I'd like to introduce you, Antoine, to Calixteman, and ask you to have a chat. IMHO, Antoine has submitted a useful improvement, and every pdf.js user should benefit from it - not just users of ngx-extended-pdf-viewer. The idea was it would be nice to be able to do one action with the pen (writing if the pen started the event) and still be able to scroll with the hand.

The improvement used to work for some time, so I can confidently say it's easy to implement. Nonetheless, I've ended up in merge hell, so I guess implementing it at the pdf.js side makes more sense than implementing it for Angular users only.

**Comment by legraina** [comment]
Hi @calixteman, I'll be happy to work with you in implementing it. It was rather easy. The tough part was finding where to remove some css style (pointer-events: none), but I think it's part of ngx-extended-pdf-viewer and not pdf.js. The modification of the pdf.js was rather easy.

**Comment by calixteman** [comment]
I'm currently refactoring the ink tool and it'll support having multiple pointer types.

**Comment by legraina** [comment]
That's great ! Do you wish to get the pieces of code that I have added if it can help you. I have also added a piece of code to avoid to load several times the worker if not needed.

**Comment by stephanrauh** [comment]
I've reverted the changes in version 22.0.0.

**Comment by legraina** [comment]
Ok, thanks.
@calixteman here is my code if it's usefull for you (I've changed it a little):
```js
class PointerType {
    static current = null;
    static editor = null;
    constructor(t) {
        if (null === PointerType.current) {
            PointerType.current = "";
            window.addEventListener("pointerdown", this.windowPointerDown, !0)
        }
    }
    destroy() {
        if (null !== PointerType.current) {
            window.removeEventListener("pointerdown", this.windowPointerDown, !0);
            PointerType.current = null
        }
    }
    windowPointerDown(t) {
        PointerType.current = t.pointerType;
        return !0
    }
    static initializeEditor() {
      setTimeout(() => PointerType.editor = PointerType.current);
    }
    static sameAsEditor(pointerType = undefined) {
      if (pointerType) {
        return PointerType.editor == pointerType;
      }
      return PointerType.editor == PointerType.current;
    }
}
new PointerType;
```

I am listening the event  "annotationeditormodechanged" in the AnnotationEditorUIManager:
```js
onAnnotationEditorModeChanged() {
  PointerType.initializeEditor();
}
```

And I've modified and added those methods associated to the right events:
```js
canvasPointerdown(t) {
    if (0 === t.button && this.isInEditMode() && !this.#ja && PointerType.sameAsEditor(t.pointerType)) {
        this.setInForeground();
        t.preventDefault();
        this.div.contains(document.activeElement) || this.div.focus({
            preventScroll: !0
        });
        this.#nr(t.offsetX, t.offsetY)
    }
}
canvasTouchMove(t) {
    this.isInEditMode() && !this.#ja && PointerType.sameAsEditor() && t.preventDefault()
}
```

**Comment by stephanrauh** [comment]
@legraina I believe your feature is back! Version 21.1.0-alpha.2 solves a weird issue by tracking the pointer ids - and that's more or less the same you did. Can you run a test, please?

**Comment by legraina** [comment]
Are you talking about commit 7a8335481a294c17c2ea4bc0a088a3935549ecab in pdf.js ? I think you fixed the issue when drawing with a finger, but you totally removed my feature where I was tracking the PointerType to remember what type of pointer you used to enable the ink editor mode.

**Comment by stephanrauh** [comment]
Yes, that's true. I removed your feature because I was totally confused when trying to resolve my merge conflict.

**Comment by stephanrauh** [comment]
I've accepted your pull request. It's good to have your feature back!
