### ISSUE TITLE
minZoom/maxZoom doesn't mean the same thing on browser/mobile?

### ISSUE THREAD

**Issue by thibaultv** [stephanrauh/ngx-extended-pdf-viewer#599]
**Describe the bug**
Hi, I'm working with @Foszcz who opened the ticket #583.

If I configure a minZoom and a maxZoom :
- On mobile, those values seems to be a minimum/maximum for **each** pinching
- On browser, those values are a minimum/maximum value that we can reach in **total**.

So for a configuration 0.5/1.5, each time I try to zoom in, it's 50% bigger and it can zoom forever 50% more.

minZoom & maxZoom seems to be, on mobile, more a pinchStep value that specify the zoom we can reach with a single pinch. 

With (zoomChange) event, I reach this value on my device : 0.0000047773429879265255 (minZoom was 0.5 in my test).

**Version info**
7.1.0

**Smartphone (please complete the following information):**
Android 10 on Samsung SM-T510

**To Reproduce**
You can use the same parameter provided in #583 .

Thanks a lot,

Kr,

Thibault

**Comment by stephanrauh** [comment]
Hi Thibault,

yeah, that sounds familiar. You're describing the bug I've solved with version 7.1.0. Or at least I believed to have solved it. 

Debugging on mobile devices is always tricky, but can you check if you've run into a caching issue? Or can you debug my code? The commit that *should* solve the issue is https://github.com/stephanrauh/ngx-extended-pdf-viewer/commit/12f8f1e4ae730fd33681a60a79efc804ced5f29e.

Best regards,
Stephan

**Comment by stephanrauh** [comment]
Oh, and reading the title of the issue: of course min and max are supposed to mean the same on desktop and on mobile. It's just a silly bug of mine. :) Remains the question if it's still there after my bug fix, and if so, what I've missed.

**Comment by thibaultv** [comment]
Hi Stephan,

Thanks for your quick answer. I'm using version 7.1.0 so if minZoom means the minimum zoom we can achieve, it's not solved.

Normally, following your code, `pinchScale` will be always 1 if minZoom or maxZoom are reached and thus no transformation occurs...

I suppose the problem is linked to a cached value or the following line [L73](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/12f8f1e4ae730fd33681a60a79efc804ced5f29e/projects/ngx-extended-pdf-viewer/src/lib/pinch-on-mobile-support.ts#L73) and [L86](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/12f8f1e4ae730fd33681a60a79efc804ced5f29e/projects/ngx-extended-pdf-viewer/src/lib/pinch-on-mobile-support.ts#L86) must maybe need adjustement.
FMY, first is to transform and second is only for setting the value right? or both applies transformation of the view?

Kr,

Thibault

**Comment by stephanrauh** [comment]
You're right. I've fixed the bug with version 7.3.1. This time for real, I hope! :)

Best regards,
Stephan

**Comment by thibaultv** [comment]
Hi @stephanrauh,

Thanks for the fix. Can you tell me how it was fixed? I don't see any commits linked. Dependencies maybe?

Happy new year by the way.

Kr,

Thibault

**Comment by stephanrauh** [comment]
No... I'd just forgotten to push the changes :)

**Comment by Foszcz** [comment]
Hi @stephanrauh 

I tested the fix but i have yet an issue  . In fact the first opening of PDF all is alright but if i try to open a second time ( without close application, you need minimum two page to make this )  the zoom are completely broken when you reach the limit max or min. 

I send you my test apk  if you want test of your side. On the version 7.3.1

[app-debug.zip](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/5787463/app-debug.zip)

**Comment by stephanrauh** [comment]
@Foszcz How can I use the APK? I don't own an Android device. And I've never worked for a mobile platform, so consider me a rookie. I seriously don't know how to use the APK, but I'm willing to learn and to give my best.

**Comment by Foszcz** [comment]
Hi @stephanrauh  , 

In fact the APK allow only to see the bug and confirm it , i will give you my test project it will be easier for you.
https://drive.google.com/drive/folders/17Ctwxdztmabj3uC01Glk4SxEyH4kkEzK?usp=sharing

but you need to follow the step here https://ionicframework.com/docs/developing/android to config android studio .

To import my project see below 

- Dezip the folder project ,
- In the top-left menu chose import project and chose folder ( a pop-up appears don't worry )  take option import project from external model and chose gradle 

I hope that will be sufficient ,don't hesitate if you have any questions

**Comment by stephanrauh** [comment]
@Foszcz Thanks! I've downloaded the file. As far as I can see, it's a just test project, but if you want to remove it from the web, you can do that safely now.

The next few days are going to be very exhausting: I'm giving my Angular training, so I'm going to talk all day long, not to mention eight hours of live coding. In other words: give me a few days time until I resume working on my pet project.

**Comment by stephanrauh** [comment]
I'm afraid I won't be able to analyze this bug any time soon. New bug reports and feature request are coming in faster I can solve them. So let me tell you how to solve the problem yourself. I think that's better, anyways: You can debug the code, test it with your real application, and tune it until it fits your need. 

Pinching is implemented in this class: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/pinch-on-mobile-support.ts

Copy this class to your project, make sure it's loaded, and disable the built-in pinch support (i.e. set [enablePinchOnMobile]="false"). The constructor of the class injects Angular's `ngZone` object. I guess it's automatically injected if you convert the class to an Angular service.

Once you've done that, your copy of the class is responsible for pinching, and you can hunt down the bug.

**Comment by Foszcz** [comment]
Hi @stephanrauh  
I found the problem , in fact in this code 

` public initializePinchZoom(): void {
    if (!this.isMobile()) {
      return;
    }
    this.viewer = document.getElementById('viewer');
    this._zone.runOutsideAngular(() => {
      document.addEventListener('touchstart', this.boundOnViewerTouchStart);
      document.addEventListener('touchmove', this.boundOnViewerTouchMove, { passive: false });
      document.addEventListener('touchend', this.boundOnViewerTouchEnd);
    });
  }

  public destroyPinchZoom(): void {
    if (!this.isMobile()) {
      return;
    }
    document.removeEventListener('touchstart', this.boundOnViewerTouchStart);
    document.removeEventListener('touchmove', this.boundOnViewerTouchMove);
    document.removeEventListener('touchend', this.boundOnViewerTouchEnd);
  }`

The remove listener doesn't work because when you call the function destroyPinchZoom the document was already change and so it's impossible to remove the listener.

I fix it in my side in modify with this 
` initializePinchZoom() {
        this.viewer = document.getElementById('viewer');
        this._zone.runOutsideAngular((/**
         * @return {?}
         */
        () => {
             this.viewer.addEventListener('touchstart', this.onViewerTouchStart.bind(this));
             this.viewer.addEventListener('touchmove', this.onViewerTouchMove.bind(this));
             this.viewer.addEventListener('touchend', this.onViewerTouchEnd.bind(this));
        }));
    }
    /**
     * @return {?}
     */
    destroyPinchZoom() {
        if (this.isMobile()) {
             this.viewer.removeEventListener('touchstart', this.onViewerTouchStart);
             this.viewer.removeEventListener('touchmove', this.onViewerTouchMove);
             this.viewer.removeEventListener('touchend', this.onViewerTouchEnd);
}
    }
`

**Comment by stephanrauh** [comment]
@jpxd contributed a similar bugfix yesterday (#713, #715). So I suppose updating to 9.0.0-alpha.2 solves the bug.

Sorry I didn't tell you earlier - I wasn't aware two developers are hunting the same bug independently!

Best regards,
Stephan
