### ISSUE TITLE
[MacOS Mojave Safari ]: pdfLoadingFailed not trigger Unexpected token error

### ISSUE THREAD

**Issue by jordankkk** [stephanrauh/ngx-extended-pdf-viewer#650]
is there any option to trigger this error ?
![vmware_uaeLxr18yz](https://user-images.githubusercontent.com/38534295/107903541-7e48d280-6f84-11eb-9d3e-25ae42543a09.png)

pdfLoadingFailed seem not trigger this error

Thanks

**Comment by stephanrauh** [comment]
Well, you've managed to take a screenshot, so obviously it is possible to trigger this error, indeed!

But I don't have a clue what's going on. I've just tried to reproduce the bug with my copy of Safari. It works like charm.

I suggest you clean your browser cache and try again. I'd also like to know if the bug - if you can reproduce it after clearing the cache - also happens on Chrome or Firefox, or if it's specific to Safari. Plus, you can switch to pdf.js 2.8. Does the bug still occur?

Of course, I can also re-deploy the showcase, but I'd like to know what's going to, so I'm going to wait for your answer patiently.

BTW, the showcase is a simple Angular application hosted at https://github.com/stephanrauh/extended-pdf-viewer-showcase/, so you can clone it and get it up and running in five minutes unless you're behind a nasty corporate firewall. If you do, you can add the attribute `[minifiedJSLibraries]="false"` to the default demo `simple.html`, which give you much more useful stack traces and line numbers.

**Comment by jordankkk** [comment]
Hi,

sorry my question is not clearly, actually i use virtual machine to test this with MacOS Mojave Safari (tested all pdf.js versions at the demo site and all is same error), regard this error possible to catch it?

MacOS Catalina is ok at all

Thanks

**Comment by stephanrauh** [comment]
Ah, now I get it! Phew, that's difficult. I'd like to help you, but I don't know how. By definition, I only support the most current versions of MacOS, simply because I can't switch to an older version. If you help me, maybe it's possible to find a solution. 

Please clone the showcase (i.e. `git clone`), add the attribute `[minifiedJSLibraries]="false"` to the broken demos, and send me the stacktrace of the error. I suppose there's a missing polyfill. But it's difficult to guess which one.

**Comment by jordankkk** [comment]
Ok, since currently i already removed the mojave and installed big sur :), give me some time i install back and try with [minifiedJSLibraries]="false"

**Comment by stephanrauh** [comment]
I believe I've found the bug - or, more precisely, Luis Santana aka @LuisManuel1983 has found the bug. pdf.js happily embraced the Elvis operator (aka null-safe chaining, or `?.`), but iOS is a bit slow supporting it. So before you install an old version of the operation system, maybe it's safe to wait until I've found a way how to force old-but-not-quite-as-old version of iOS to use the ES5 build.

**Comment by stephanrauh** [comment]
I've just published version 8.1.2 of ngx-extended-pdf-viewer. I believe it fixes the bug - but since it doesn't happen on any of my machines, I need you. Would you mind to run a test and tell me if the new version fixes the bug or not?

**Comment by jordankkk** [comment]
Ok no problem once i install back Mojave i will test again in this week

thanks @stephanrauh

**Comment by jordankkk** [comment]
@stephanrauh so far tested onPdfLoadingFailed still not trigger 

![mojave](https://user-images.githubusercontent.com/38534295/109376581-754eee00-7900-11eb-957b-1b631962cc72.png)

**Comment by jordankkk** [comment]
the error is same when set to [minifiedJSLibraries]="false"

![image](https://user-images.githubusercontent.com/38534295/109377062-c6141600-7903-11eb-919d-c2c84081b57a.png)

**Comment by stephanrauh** [comment]
You're lucky - I just found out that Browserstack offers free testing for open source developers, so I managed to confirm you bug report. Bad luck for me. :)

**Comment by stephanrauh** [comment]
Please update to version 8.2.0. It finally fixes the bug.
