### ISSUE TITLE
Single paged pdf print issue

### ISSUE THREAD

**Issue by athiraPadmanabhan** [stephanrauh/ngx-extended-pdf-viewer#698]
![Screenshot (142)](https://user-images.githubusercontent.com/81011358/111864663-589a5900-8988-11eb-855f-fd0e20cf2f17.png)
I am using [ngx-extended-pdf-viewer(4.0.0-alpha.5)) in Angular 8 and pdfs are showing up correctly except for when I am using single paged pdfs. For single paged pdfs, the preview is blank.

**Comment by stephanrauh** [comment]
That doesn't happen on https://pdfviewer.net/extended-pdf-viewer/page-view-model. So I suspect that's a problem caused by your CSS rules.

BTW, did you try updating to a current version? Maybe it's a bug I've fixed in the meantime.

**Comment by athiraPadmanabhan** [comment]
For multiple paged pdf, its working fine, and also I have tried with the
latest version.But issue is still there for single page pdf

**Comment by athiraPadmanabhan** [comment]
Its resolved

**Comment by athiraPadmanabhan** [comment]
Its resolved by adding the css rules
@media print {
    #printContainer>div {
        display: inline;
    }
}

**Comment by stephanrauh** [comment]
That's great news! Plus extra kudos for telling us which CSS rule was broken!

Best regards,
Stephan

**Comment by stephanrauh** [comment]
I've went over the print CSS again. When you update to version 9.0.0, your bugfix stops working. I believe you won't need the workaround once you've updated.
