### ISSUE TITLE
pdf image not loaded at all

### ISSUE THREAD

**Issue by wilson3q** [stephanrauh/ngx-extended-pdf-viewer#748]
On version 9.0+, the PDF image is not loaded at all upon setting the "src" URL, spinner keeps on turning but with totally blank images. The PDF Images only start to load once  you scroll it or click the viewer or zoom it...

Version 8 has no problem at all.

Please fix, thank!

**Comment by stephanrauh** [comment]
I noticed this problem with Base64 files. But when I tried to investigate the topic, the bug was gone.

Are you loading the PDF file with a REST call? If you do, can you modify your application so that the PDF viewer is opened after the PDF file has been loaded? That's not a workaround, it's just something I'd like to test. I suspect the problem occurs only if the PDF viewer is opened with an empty `[src]` attribute. When `[src]` gets a sensible value later, the PDF viewer doesn't initialize correctly. 

At the moment, this is only a theory. Can you help me to find out if it's correct, please?

**Comment by wilson3q** [comment]
Thanks for you reply. I use ngx-exteneded-pdf-viewer (in an angular application), which is faster than browser's native pdf renderer. First I call one rest API to generate the PDF first, then get the PDF image URL. Then only if the URL is not empty, a Mat Dialog with pdf viewer is opened. Version 8 opens it properly without any issues. But version 9 has problems.

**Comment by stephanrauh** [comment]
I've just published version 9.0.0-alpha.6 with a sightly optimized initialization. Maybe it solves you issue.

**Comment by wilson3q** [comment]
sorry, tried alpah6, still not good. spinner is loading non-stop...only you zoom it or scroll it, it displays the actual image.

**Comment by stephanrauh** [comment]
Please clone the showcase(https://github.com/stephanrauh/extended-pdf-viewer-showcase) and start it. It's a simple Angular project, so it's just a matter of five minutes. Do the PDF files render in the showcase? Or does the error happen there, too?

**Comment by wilson3q** [comment]
I tried the showcase app. when i navigate to "http://localhost:4200/extended-pdf-viewer/contextmenu", it shows blank page very long before it starts showing the actual image. But if I clicked zoom button, it shows immediately.

**Comment by stephanrauh** [comment]
I've managed to reproduce both the bug and the workaround. So I can finally hunt it down. Thanks a lot!

**Comment by stephanrauh** [comment]
Good news: version 9.0.0-alpha.7 fixes the bug. In hindsight, it was an obvious bug - I was just distracted, so I didn't see it.

Thanks for being persistent!

Best regards,
Stephan

**Comment by wilson3q** [comment]
Thanks for your support!
It can display the image now...but a lot slower than v8.3. Do you know why? v8.3 display PDF images almost instantly, while on v9 the spinner keep on turning and turning, a few seconds later it shows.

**Comment by stephanrauh** [comment]
Is version 9.0.0-alpha.0 still OK, while 9.0.0-alpha.1 is already broken?

BTW, setting the `[zoom]` might help. Since version 9.0.0-alpha.1, I'm trying to use the setting the user used when they where looking precisely at that file. Unfortunately, this results in a delay because the file has to be loaded first to calculate the fingerprint of the file.

**Comment by wilson3q** [comment]
I have no choice but to stick with v8.3 now...as it is the most fast and stable version for now.

**Comment by wilson3q** [comment]
I opened browser developer console, see the errors below while loading the PDF image. Please check if this is helpful.

```
PDFViewer.scrollPageIntoView: "1" is not a valid pageNumber parameter. base_viewer.js:916:6
    scrollPageIntoView base_viewer.js:916
    _setScaleUpdatePages base_viewer.js:761
    _setScale base_viewer.js:802
    set currentScaleValue base_viewer.js:397
    setZoom main-es2015.051d56da89e5eaa20f4c.js:1
    OB main-es2015.051d56da89e5eaa20f4c.js:1
    P polyfills-es2015.9277284ec60079fdc50a.js:1
    OB main-es2015.051d56da89e5eaa20f4c.js:1
    setZoom main-es2015.051d56da89e5eaa20f4c.js:1
    openPDF main-es2015.051d56da89e5eaa20f4c.js:1
    OB main-es2015.051d56da89e5eaa20f4c.js:1
    P polyfills-es2015.9277284ec60079fdc50a.js:1
    OB main-es2015.051d56da89e5eaa20f4c.js:1
    openPDF main-es2015.051d56da89e5eaa20f4c.js:1
    0 polyfills-es2015.9277284ec60079fdc50a.js:1
    invokeTask polyfills-es2015.9277284ec60079fdc50a.js:1
    onInvokeTask main-es2015.051d56da89e5eaa20f4c.js:1
    invokeTask polyfills-es2015.9277284ec60079fdc50a.js:1
    runTask polyfills-es2015.9277284ec60079fdc50a.js:1
    invokeTask polyfills-es2015.9277284ec60079fdc50a.js:1
    invoke polyfills-es2015.9277284ec60079fdc50a.js:1
    0 polyfills-es2015.9277284ec60079fdc50a.js:1
    (Async: setTimeout handler)
    i polyfills-es2015.9277284ec60079fdc50a.js:1
    scheduleTask polyfills-es2015.9277284ec60079fdc50a.js:1
    onScheduleTask polyfills-es2015.9277284ec60079fdc50a.js:1
    scheduleTask polyfills-es2015.9277284ec60079fdc50a.js:1
    scheduleTask polyfills-es2015.9277284ec60079fdc50a.js:1
    scheduleMacroTask polyfills-es2015.9277284ec60079fdc50a.js:1
    l polyfills-es2015.9277284ec60079fdc50a.js:1
    r polyfills-es2015.9277284ec60079fdc50a.js:1
    o polyfills-es2015.9277284ec60079fdc50a.js:1
    openPDF main-es2015.051d56da89e5eaa20f4c.js:1
    invoke polyfills-es2015.9277284ec60079fdc50a.js:1
    onInvoke main-es2015.051d56da89e5eaa20f4c.js:1
    invoke polyfills-es2015.9277284ec60079fdc50a.js:1
    run polyfills-es2015.9277284ec60079fdc50a.js:1
    Z polyfills-es2015.9277284ec60079fdc50a.js:1
    invokeTask polyfills-es2015.9277284ec60079fdc50a.js:1
    onInvokeTask main-es2015.051d56da89e5eaa20f4c.js:1
    invokeTask polyfills-es2015.9277284ec60079fdc50a.js:1
    runTask polyfills-es2015.9277284ec60079fdc50a.js:1
    m polyfills-es2015.9277284ec60079fdc50a.js:1
    (Async: promise callback)
    _ polyfills-es2015.9277284ec60079fdc50a.js:1
    scheduleTask polyfills-es2015.9277284ec60079fdc50a.js:1
    scheduleTask polyfills-es2015.9277284ec60079fdc50a.js:1
    scheduleMicroTask polyfills-es2015.9277284ec60079fdc50a.js:1
    Z polyfills-es2015.9277284ec60079fdc50a.js:1
    then polyfills-es2015.9277284ec60079fdc50a.js:1
    (Async: promise callback)
    get genericl10n.js:42
    _updateUIState toolbar.js:191
    setPagesCount toolbar.js:107
    load app.js:1335
    open app.js:1010
    invoke polyfills-es2015.9277284ec60079fdc50a.js:1
    onInvoke main-es2015.051d56da89e5eaa20f4c.js:1
    invoke polyfills-es2015.9277284ec60079fdc50a.js:1
    run polyfills-es2015.9277284ec60079fdc50a.js:1
    Z polyfills-es2015.9277284ec60079fdc50a.js:1
    invokeTask polyfills-es2015.9277284ec60079fdc50a.js:1
    onInvokeTask main-es2015.051d56da89e5eaa20f4c.js:1
    invokeTask polyfills-es2015.9277284ec60079fdc50a.js:1
    runTask polyfills-es2015.9277284ec60079fdc50a.js:1
    m polyfills-es2015.9277284ec60079fdc50a.js:1
    invokeTask polyfills-es2015.9277284ec60079fdc50a.js:1
    p polyfills-es2015.9277284ec60079fdc50a.js:1
    f polyfills-es2015.9277284ec60079fdc50a.js:1
    (Async: EventListener.handleEvent)
    P polyfills-es2015.9277284ec60079fdc50a.js:1
    scheduleTask polyfills-es2015.9277284ec60079fdc50a.js:1
    onScheduleTask polyfills-es2015.9277284ec60079fdc50a.js:1
    scheduleTask polyfills-es2015.9277284ec60079fdc50a.js:1
    scheduleTask polyfills-es2015.9277284ec60079fdc50a.js:1
    scheduleEventTask polyfills-es2015.9277284ec60079fdc50a.js:1
    A polyfills-es2015.9277284ec60079fdc50a.js:1
    MessageHandler pdf_history.js:192
    _initialize app.js:1
    PDFWorker app.js:2785
    getDocument app.js:1702
    open app.js:938
```

**Comment by wilson3q** [comment]
If I set "listenToURL" to true, the image was loaded properly without any delays. This is my workaround to use v9 for now.

**Comment by stephanrauh** [comment]
Reopened because of the interesting stacktrace. `open()` -> `setPagesCount()` -> `openPDF()` -> `setZoom()` -> `scrollPageIntoView()` -> `1 is not a valid page number` isn't what I expected. Maybe `scrollPageIntoView()` is called before the page has been rendered?

**Comment by wilson3q** [comment]
I traced with event pdfLoaded, it is called after pdfLoaded event, but before pagesLoaded....

**Comment by stephanrauh** [comment]
Thanks for the hint!
